POST http://localhost:8096/cxf/server
Content-Type: application/json

{
  "address": "http://localhost:8081/cxf/test",
  "wsdlUrl": "http://localhost:8099/weather?wsdl",
  "dataFormat": "RAW",
  "loggingFeatureEnabled": false
}

###
POST http://localhost:8093/weather
Content-Type: application/json

{
"name": "wweeweweewe"
}

### RAW
POST http://localhost:8096/test/www
Content-Type: application/json

{

}

### RAW
POST http://localhost:8096/cxf/raw
Content-Type: application/json

{

}

### payload
POST http://localhost:8096/cxf/payload
Content-Type: application/json

{

}



###
POST http://172.16.110.174:8099/weather
Content-Type: text/xml

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <ns2:hellworld xmlns:ns2="http://webservice.gkq.cn/">
            <ns2:city>chengdu1111111111111111</ns2:city>
            <ns2:name>sfasdfsdfsdfs</ns2:name>
        </ns2:hellworld>
    </soap:Body>
</soap:Envelope>


###
POST http://localhost:8088/payload
Content-Type: text/xml

<ns2:queryWeather xmlns:ns2="http://impl.webservice.gkq.cn/">
    <arg0>beijing</arg0>
</ns2:queryWeather>